### ISSUE TITLE
Safari app crashing for Safari Plus 1.6.8-3 on iOS 12.2

### ISSUE THREAD

**Issue by cemerson** [opa334/SafariPlus#12]
Apologies if this has been reported already (realize the 12.2 jailbreak(s) *just* came out other day). Just reporting that Safari crashing w/version Safari Plus 1.6.8-3 on iOS 12.2 right now. 
Here's my CrashReporter log if helpful: https://gist.github.com/cemerson/c22735e2380b1535ea79d93e8f06b101

**Comment by yousef157** [comment]
Try updating. There's a 1.7~b7 version at the repo https://opa334.github.io/beta/

**Comment by opa334** [comment]
The same crash happens on 1.7~b7 too.

I'm right now trying to get the 12.2 simulator working so I can fix this. The final build of 1.7 with 12.2 support will be released shortly.

**Comment by yousef157** [comment]
> The same crash happens on 1.7~b7 too.
> 
> I'm right now trying to get the 12.2 simulator working so I can fix this. The final build of 1.7 with 12.2 support will be released shortly.

Alright, so close issue when fixed, yeah?

**Comment by coenkcore** [comment]
same error on iOS 12.2 with Safari Plus 1.7~b7
safari keep crashing while tweak installed

**Comment by Kai0KenX20** [comment]
Any update? I really miss my safari plus :(

**Comment by opa334** [comment]
Fixed tons of stuff today. Will probably release beta 8 with 12.2 support tomorrow. Maybe even sooner, will see.

**Comment by Kai0KenX20** [comment]
Awesome! Thanks for the quick reply and also for all your hard work buddy if you need a tester I’m down 👍 on 6s+

**Comment by slio** [comment]
Safari still crashing on latest beta, 1.7~b8, It opens fine however after 2-3 minutes of browsing it auto crashes. 
Sometimes it just crashes when opening/clicking on a link.

**Comment by opa334** [comment]
"Force HTTPS" and "Open all Links in Background" are broken and will be fixed soon in 1.7. Speaking of that, maybe there are more issues than I know of, please send all your crash reports of Safari via CrashReporter to opa334@protonmail.com.

**Comment by Kai0KenX20** [comment]
I’d post crash logs for ya np if it actually gave me any :( every time it crashes when using certain links https etc I don’t get any using cr4shed is their something better?

**Comment by opa334** [comment]
Cr4shed only logs specific issues but provides better information. CrashReporter logs everything but provides less information.

**Comment by slio** [comment]
Hi, 

Attaching log,
https://ybin.me/p/c61a90a32dca82f1#e6N1ouTGup4Aq7pKvxszQTolh1fcrPpG9FVsJbiJ/Y4=
Let me know what else might help you resolve this.
I have tried switching Force HTTPS OFF, it still crashes.

**Comment by opa334** [comment]
To everone affected, please test this deb: http://www.mediafire.com/file/q6vddny8cvqkjzm/com.opa334.safariplus_1.7%257Eb8-3-1%252Bdebug_iphoneos-arm.deb/file

There should be no more crashes left, please let me know if I'm wrong and attach a crash log.

**Comment by slio** [comment]
works like a charm! @opa334
